### PR TITLE
added scripts for pubmed citation metadata extraction

### PR DESCRIPTION
**Pull request by rdharjai**
added two files:
- geniepy/src/geniepy/scripts/citation_cloud_function.py
- geniepy/src/geniepy/scripts/citation_historical.py

### CODE REVIEW

**Comment by derekkinzo** [comment]
@rdharjai the scripts look good, thanks for putting them on correct location... so far I was being diligent about some things like linter errors and didn't have any, some of the scripts have some (see CI results under "lint with flake8": https://github.com/derekkinzo/genie/pull/23/checks?check_run_id=624526709) - I'm not sure how much this matters, so up to you, if you feel like fixing them go ahead. Otherwise, let me know and I'll merge this in

**Comment by derekkinzo** [comment]
@rdharjai also, I think we would benefit from module docstrings (triple quote comments at top of each file) describing purpose and how to use each module. This would be especially useful for code review (Roman) - Not a requirement either

**Comment by rdharjai** [comment]
done!

**Comment by rdharjai** [comment]
done!

**Pull request merged**
